wandb_version: 1

V:
  value: 8739
architecture:
  value: cnn
batch_size:
  value: 16
data_frac:
  value: 0.005
dataset:
  value: sdss
device:
  value:
  - cuda
dropout:
  value: 0.1
emb_size:
  value: 100
epochs:
  value: 2
hidden_size:
  value: 512
if_aware:
  value: 1
kernel:
  value: 3
lr:
  value: 0.001
num_layers:
  value: 6
patience:
  value: 3
problem:
  value: fragment
