wandb_version: 1

V:
  value: 8738
architecture:
  value: rnn
batch_size:
  value: 256
data_frac:
  value: 0.005
dataset:
  value: sdss
device:
  value:
  - cpu
dropout:
  value: 0.2
emb_size:
  value: 512
epochs:
  value: 2
hidden_size:
  value: 256
lr:
  value: 0.0001
num_layers:
  value: 6
patience:
  value: 3
problem:
  value: fragment
