wandb_version: 1

V:
  desc: null
  value: 8738
_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.7.4
      5: 0.10.30
      8:
      - 3
      - 5
architecture:
  desc: null
  value: rnn
batch_size:
  desc: null
  value: 256
data_frac:
  desc: null
  value: 0.005
dataset:
  desc: null
  value: sdss
device:
  desc: null
  value:
  - cpu
dropout:
  desc: null
  value: 0.2
emb_size:
  desc: null
  value: 512
epochs:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0001
num_layers:
  desc: null
  value: 6
patience:
  desc: null
  value: 3
problem:
  desc: null
  value: fragment
