wandb_version: 1

V:
  value: 8739
architecture:
  value: cnn
batch_size:
  value: 16
data_frac:
  value: 0.005
device:
  value:
  - cpu
dropout:
  value: 0
emb_size:
  value: 100
epochs:
  value: 2
hidden_size:
  value: 1024
lr:
  value: 0.001
patience:
  value: 3
