wandb_version: 1

V:
  value: 8738
architecture:
  value: rnn
batch_size:
  value: 16
data_frac:
  value: 0.005
device:
  value:
  - cpu
dropout:
  value: 0.2
emb_size:
  value: 500
epochs:
  value: 2
hidden_size:
  value: 1024
lr:
  value: 0.001
patience:
  value: 3
