wandb_version: 1

V:
  value: 8739
batch_size:
  value: 64
data_frac:
  value: 0.005
device:
  value:
  - cpu
dropout:
  value: 0.3
emb_size:
  value: 100
epochs:
  value: 2
hidden_size:
  value: 512
kernel:
  value: 3
lr:
  value: 0.001
num_layers:
  value: 2
patience:
  value: 3
