# Depending on the result of HP tuning
setup:
    dataset: sqlshare
    template_min_count: 3 # sdss: 9, sqlshare: 3
    architecture: 'transformer' #'transformer', 'rnn', 'cnn'
constant: 
    emb_size: 512
    hidden_size: 2048
    num_layers: 2
    heads: 16
    dropout: 0.3
    output_size: 512 # emb_size
    V: null