wandb_version: 1

V:
  desc: null
  value: 8739
_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.7.9
      5: 0.10.13
architecture:
  desc: null
  value: cnn
batch_size:
  desc: null
  value: 64
data_frac:
  desc: null
  value: 0.005
dataset:
  desc: null
  value: sdss
device:
  desc: null
  value:
  - cuda
dropout:
  desc: null
  value: 0.3
emb_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 256
if_aware:
  desc: null
  value: 1
kernel:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 6
patience:
  desc: null
  value: 3
problem:
  desc: null
  value: fragment
